## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://10.0.0.174:9200
elasticsearch.username: kibana
elasticsearch.password: puwPGAVCVN0mnCqzlbFd
